Repository darint916/Chord-KTV, pull requests merged in 2025-05, with the labels that each got.

#235 Song search fixes prompts
  ChordKTV/Services/Service/ChatGptService.cs
  frontend/lyric-sync-app/src/pages/SongPlayerPage/SongPlayerPage.tsx
Labels: bug, finish asap

#236 init handwriting phrase creation and rom + trans
  ChordKTV/Controllers/HandwritingController.cs
  ChordKTV/Dtos/OpenAI/Phrases.cs
  ChordKTV/Dtos/OpenAI/TranslatePhrasesRequestDto.cs
  ChordKTV/Dtos/OpenAI/TranslatePhrasesResponseDto.cs
  ChordKTV/Services/Api/IChatGptService.cs
  ChordKTV/Services/Service/ChatGptService.cs
  frontend/lyric-sync-app/src/api/.openapi-generator/FILES
  frontend/lyric-sync-app/src/api/apis/HandwritingApi.ts
  frontend/lyric-sync-app/src/api/models/Phrases.ts
  frontend/lyric-sync-app/src/api/models/TranslatePhrasesResponseDto.ts
  frontend/lyric-sync-app/src/api/models/index.ts
  frontend/lyric-sync-app/swagger.json
Labels: enhancement, prio: HIGH

#238 Frontend handwriting quiz redesign
  frontend/lyric-sync-app/src/components/HandwritingCanvas/HandwritingCanvas.scss
  frontend/lyric-sync-app/src/components/HandwritingCanvas/HandwritingCanvas.tsx
  frontend/lyric-sync-app/src/components/LyricDisplay/LyricDisplay.tsx
  frontend/lyric-sync-app/src/components/QuizComponent/QuizComponent.scss
  frontend/lyric-sync-app/src/components/QuizComponent/QuizComponent.tsx
  frontend/lyric-sync-app/src/contexts/SongContext.ts
  frontend/lyric-sync-app/src/contexts/SongContextProvider.tsx
  frontend/lyric-sync-app/src/pages/HandwritingPage/HandwritingPage.scss
  frontend/lyric-sync-app/src/pages/HandwritingPage/HandwritingPage.tsx
  frontend/lyric-sync-app/src/pages/SongPlayerPage/SongPlayerPage.tsx
Labels: enhancement, refactor, prio: HIGH, finish asap

#242 Deployment Guide
  docs/DEPLOYMENT.md
Labels: documentation
