Repository darint916/Chord-KTV, pull requests merged in 2025-02, with the labels that each got.

#3 Style guide
  .editorconfig
  .github/pull_request_template.md
  .github/workflows/enforce-code-style.yml
  .github/workflows/pr-description-validation.yml
  .idea/.gitignore
  .idea/Chord-KTV.iml
  .idea/modules.xml
  .idea/vcs.xml
  ChordKTV/ChordKTV.csproj
  ChordKTV/Controllers/SongController.cs
  ChordKTV/Controllers/WeatherForecastController.cs
  ChordKTV/Models/SongData/Album.cs
  ChordKTV/Models/SongData/GeniusMetaData.cs
  ChordKTV/Models/SongData/Song.cs
  ChordKTV/Models/UserData/User.cs
  ChordKTV/Services/Api/IGeniusRepo.cs
  ChordKTV/Services/Api/IGeniusService.cs
  ChordKTV/Services/Context/DbContext.cs
  ChordKTV/Services/Service/GeniusRepo.cs
  ChordKTV/Services/Service/GeniusService.cs
  ChordKTV/WeatherForecast.cs
Labels: enhancement, system config

#5 Database init
  .editorconfig
  .gitattributes
  .github/pull_request_template.md
  .github/workflows/pr-description-validation.yml
  .idea/dataSources.xml
  ChordKTV/Data/AppDbContext.cs
  ChordKTV/Data/PrebDb.cs
  ChordKTV/Migrations/20250202042444_InitialCreate.Designer.cs
  ChordKTV/Migrations/20250202042444_InitialCreate.cs
  ChordKTV/Migrations/AppDbContextModelSnapshot.cs
  ChordKTV/Program.cs
  ChordKTV/Services/Api/IGeniusService.cs
  ChordKTV/Services/Context/DbContext.cs
  ChordKTV/Services/Service/GeniusService.cs
Labels: enhancement, system config

#2 youtube playlist info endpoint
  .editorconfig
  ChordKTV/ChordKTV.csproj
  ChordKTV/Controllers/SongController.cs
  ChordKTV/Models/ApiModels/PlaylistDetailsDto.cs
  ChordKTV/Models/ApiModels/VideoInfo.cs
  ChordKTV/Program.cs
  ChordKTV/Services/Api/IYouTubeService.cs
  ChordKTV/Services/Service/YouTubeService.cs
Labels: enhancement

#8 Add LRCLIB query endpoint, update README DB instr.
  ChordKTV/ChordKTV.csproj
  ChordKTV/Controllers/SongController.cs
  ChordKTV/Data/PrebDb.cs
  ChordKTV/Program.cs
  ChordKTV/README.md
  ChordKTV/Services/Api/ILRCService.cs
  ChordKTV/Services/Api/IYouTubeService.cs
  ChordKTV/Services/Service/LRCService.cs
  ChordKTV/Services/Service/YouTubeService.cs
Labels: documentation, enhancement

#11 Backend basic repo creation and dev endpoint testing and refactoring
  .editorconfig
  .github/pull_request_template.md
  .github/workflows/pr-description-validation.yml
  ChordKTV/ChordKTV.http
  ChordKTV/Controllers/SongController.cs
  ChordKTV/Data/Api/SongData/IAlbumRepo.cs
  ChordKTV/Data/Api/SongData/ISongRepo.cs
  ChordKTV/Data/Api/UserData/IUserRepo.cs
  ChordKTV/Data/PrepDb.cs
  ChordKTV/Data/Repo/SongData/AlbumRepo.cs
  ChordKTV/Data/Repo/SongData/SongRepo.cs
  ChordKTV/Data/Repo/UserData/UserRepo.cs
  ChordKTV/Dtos/PlaylistDetailsDto.cs
  ChordKTV/Dtos/VideoInfo.cs
  ChordKTV/Program.cs
  ChordKTV/Services/Api/ILrcService.cs
  ChordKTV/Services/Api/IYouTubeService.cs
  ChordKTV/Services/Service/LrcService.cs
  ChordKTV/Services/Service/YouTubeClientService.cs
  ChordKTV/Utils/Extensions/DevelopmentOnly.cs
  ChordKTV/Utils/Extensions/README
Labels: documentation, enhancement, system config, refactor

#14 GitHub actions build run dotnet
  .github/workflows/dotnet-build-run-check.yml
  ChordKTV/Controllers/SongController.cs
  ChordKTV/README.md
  ChordKTV/appsettings.json
Labels: system config

#17 Backend open ai endpoint
  .editorconfig
  ChordKTV/ChordKTV.csproj
  ChordKTV/Controllers/SongController.cs
  ChordKTV/Dtos/LanguageCodeEnum.cs
  ChordKTV/Dtos/TranslationRequestDto.cs
  ChordKTV/Dtos/TranslationResponseDto.cs
  ChordKTV/Program.cs
  ChordKTV/README.md
  ChordKTV/Services/Api/IChatGptService.cs
  ChordKTV/Services/Service/ChatGptService.cs
  ChordKTV/Utils/SafeEnumConverter.cs
  README.md
Labels: enhancement, refactor, prio: HIGH

#26 Frontend
  frontend/lyric-sync-app/.gitignore
  frontend/lyric-sync-app/README.md
  frontend/lyric-sync-app/eslint.config.js
  frontend/lyric-sync-app/index.html
  frontend/lyric-sync-app/package-lock.json
  frontend/lyric-sync-app/package.json
  frontend/lyric-sync-app/public/vite.svg
  frontend/lyric-sync-app/src/App.tsx
  frontend/lyric-sync-app/src/assets/react.svg
  frontend/lyric-sync-app/src/components/AppBarComponent.tsx
  frontend/lyric-sync-app/src/components/Controls.tsx
  frontend/lyric-sync-app/src/components/LyricDisplay.tsx
  frontend/lyric-sync-app/src/components/YouTubePlayer.tsx
  frontend/lyric-sync-app/src/index.css
  frontend/lyric-sync-app/src/main.tsx
  frontend/lyric-sync-app/src/pages/HomePage.tsx
  frontend/lyric-sync-app/src/pages/SongPlayerPage.tsx
  frontend/lyric-sync-app/src/vite-env.d.ts
  frontend/lyric-sync-app/tsconfig.app.json
  frontend/lyric-sync-app/tsconfig.json
  frontend/lyric-sync-app/tsconfig.node.json
  frontend/lyric-sync-app/vite.config.ts
Labels: enhancement, prio: MED

#28 youtube api gets artist name of the video owner not of the playlist owner
  ChordKTV/Services/Service/YouTubeClientService.cs
Labels: bug, prio: MED

#24 Backend lrcapi romanized
  .editorconfig
  ChordKTV/Controllers/SongController.cs
  ChordKTV/Dtos/LrcLyricsDto.cs
  ChordKTV/Services/Api/ILrcService.cs
  ChordKTV/Services/Service/ChatGptService.cs
  ChordKTV/Services/Service/LrcService.cs
  ChordKTV/Services/Service/YouTubeClientService.cs
  ChordKTV/Utils/Extensions/DevelopmentOnly.cs
Labels: bug, enhancement, prio: HIGH

#43 Backend rest api controller refactor
  ChordKTV/Controllers/SongController.cs
  ChordKTV/Services/Api/IChatGptService.cs
  ChordKTV/Services/Api/IGeniusService.cs
  ChordKTV/Services/Api/ILrcService.cs
  ChordKTV/Services/Api/IYouTubeService.cs
  ChordKTV/Services/Service/ChatGptService.cs
  ChordKTV/Services/Service/GeniusService.cs
  ChordKTV/Services/Service/LrcService.cs
  ChordKTV/Services/Service/YouTubeClientService.cs
  ChordKTV/Utils/SafeEnumConverter.cs
Labels: refactor

#58 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report🐛-.md
  .github/ISSUE_TEMPLATE/✨feature-request.md
Labels: documentation, prio:LOW

#57 Backend lrc search tuning
  ChordKTV/Controllers/SongController.cs
  ChordKTV/Dtos/LrcLyricsDto.cs
  ChordKTV/README.md
  ChordKTV/Services/Api/ILrcService.cs
  ChordKTV/Services/Service/FullSongService.cs
  ChordKTV/Services/Service/LrcService.cs
Labels: bug, enhancement, refactor, prio: HIGH

#61 Handwriting Canvas Input
  frontend/lyric-sync-app/package-lock.json
  frontend/lyric-sync-app/package.json
  frontend/lyric-sync-app/src/App.tsx
  frontend/lyric-sync-app/src/components/AppBarComponent.tsx
  frontend/lyric-sync-app/src/components/HandwritingCanvas.tsx
  frontend/lyric-sync-app/src/pages/HandwritingPage.tsx
  frontend/lyric-sync-app/src/pages/SongPlayerPage.tsx
Labels: enhancement, prio: HIGH

#62 workflow added, bit of package change
  .github/workflows/enforce-code-style.yml
  .github/workflows/frontend-code-style.yml
  .github/workflows/react-build-check.yml
  ChordKTV/README.md
  frontend/lyric-sync-app/README.md
  frontend/lyric-sync-app/eslint.config.js
  frontend/lyric-sync-app/package-lock.json
  frontend/lyric-sync-app/package.json
  frontend/lyric-sync-app/src/components/Controls.tsx
  frontend/lyric-sync-app/src/components/HandwritingCanvas.tsx
  frontend/lyric-sync-app/src/components/YouTubePlayer.tsx
  frontend/lyric-sync-app/src/main.tsx
  frontend/lyric-sync-app/src/pages/HandwritingPage.tsx
  frontend/lyric-sync-app/src/pages/HomePage.tsx
  frontend/lyric-sync-app/src/pages/SongPlayerPage.tsx
  frontend/lyric-sync-app/tsconfig.json
  frontend/lyric-sync-app/vite.config.ts
Labels: documentation, refactor, prio:LOW

#63 Frontend auth setup
  ChordKTV/Controllers/UserController.cs
  README.md
  frontend/lyric-sync-app/.env.example
  frontend/lyric-sync-app/.gitignore
  frontend/lyric-sync-app/package-lock.json
  frontend/lyric-sync-app/package.json
  frontend/lyric-sync-app/src/App.tsx
  frontend/lyric-sync-app/src/components/AppBarComponent.tsx
  frontend/lyric-sync-app/src/config/google-auth.ts
  frontend/lyric-sync-app/src/contexts/AuthContext.tsx
  frontend/lyric-sync-app/src/contexts/authTypes.ts
  frontend/lyric-sync-app/src/pages/HomePage.tsx
Labels: enhancement, prio: MED

#66 logging added
  ChordKTV/ChordKTV.csproj
  ChordKTV/Program.cs
Labels: enhancement, prio:LOW

#68 Genius lyrics search
  ChordKTV/Controllers/SongController.cs
  ChordKTV/Program.cs
  ChordKTV/Services/Api/IGeniusService.cs
  ChordKTV/Services/Service/FullSongService.cs
  ChordKTV/Services/Service/GeniusService.cs
Labels: bug, enhancement, prio:LOW

#69 fisher yates shuffle
  ChordKTV/Controllers/SongController.cs
  ChordKTV/Services/Api/IYouTubeClientService.cs
  ChordKTV/Services/Service/YouTubeClientService.cs
  ChordKTV/Utils/Shuffle.cs
Labels: enhancement, prio:LOW

#67 Add Google Vision API OCR to Backend for Handwriting Recognition
  ChordKTV/ChordKTV.csproj
  ChordKTV/Controllers/HandwritingController.cs
  ChordKTV/Dtos/HandwritingCanvas/HandwritingCanvasRequestDto.cs
  ChordKTV/Dtos/HandwritingCanvas/HandwritingCanvasResponseDto.cs
  ChordKTV/Program.cs
  ChordKTV/README.md
  ChordKTV/Services/Api/IHandwritingService.cs
  ChordKTV/Services/Service/HandwritingService.cs
Labels: enhancement, prio: MED

#71 Backend lrc search coverage fix
  .editorconfig
  ChordKTV/Controllers/SongController.cs
  ChordKTV/README.md
  ChordKTV/Services/Api/ILrcService.cs
  ChordKTV/Services/Service/FullSongService.cs
  ChordKTV/Services/Service/LrcService.cs
  ChordKTV/Utils/CompareUtils.cs
  ChordKTV/Utils/KeywordExtractorUtils.cs
  ChordKTV/Utils/TextUtils.cs
Labels: documentation, enhancement, refactor, prio: HIGH

#79 Backend integration lyrics implementation
  ChordKTV/Controllers/SongController.cs
  ChordKTV/Data/Api/SongData/ISongRepo.cs
  ChordKTV/Data/Repo/SongData/SongRepo.cs
  ChordKTV/Dtos/FullSong/FullSongRequestDto.cs
  ChordKTV/Program.cs
  ChordKTV/Services/Api/IFullSongService.cs
  ChordKTV/Services/Service/FullSongService.cs
  ChordKTV/Services/Service/GeniusService.cs
  ChordKTV/Utils/KeywordExtractorUtils.cs
Labels: enhancement, refactor, prio: HIGH

#80 improved genius search /search endpoint
  ChordKTV/Services/Service/GeniusService.cs
Labels: bug, prio: MED

#73 Add generated OpenAPI call to frontend for OCR
  .github/workflows/react-build-check.yml
  ChordKTV/Program.cs
  frontend/lyric-sync-app/README.md
  frontend/lyric-sync-app/src/api/.openapi-generator-ignore
  frontend/lyric-sync-app/src/api/.openapi-generator/FILES
  frontend/lyric-sync-app/src/api/.openapi-generator/VERSION
  frontend/lyric-sync-app/src/api/apis/HandwritingApi.ts
  frontend/lyric-sync-app/src/api/apis/SongApi.ts
  frontend/lyric-sync-app/src/api/apis/UserApi.ts
  frontend/lyric-sync-app/src/api/apis/index.ts
  frontend/lyric-sync-app/src/api/index.ts
  frontend/lyric-sync-app/src/api/models/Album.ts
  frontend/lyric-sync-app/src/api/models/FullSongRequestDto.ts
  frontend/lyric-sync-app/src/api/models/GeniusMetaData.ts
  frontend/lyric-sync-app/src/api/models/HandwritingCanvasDto.ts
  frontend/lyric-sync-app/src/api/models/HandwritingCanvasRequestDto.ts
  frontend/lyric-sync-app/src/api/models/HandwritingCanvasResponseDto.ts
  frontend/lyric-sync-app/src/api/models/LanguageCode.ts
  frontend/lyric-sync-app/src/api/models/Song.ts
  frontend/lyric-sync-app/src/api/models/TranslationRequestDto.ts
  frontend/lyric-sync-app/src/api/models/index.ts
  frontend/lyric-sync-app/src/api/runtime.ts
  frontend/lyric-sync-app/src/components/AppBarComponent.tsx
  frontend/lyric-sync-app/src/components/HandwritingCanvas.tsx
  frontend/lyric-sync-app/swagger.json
Labels: enhancement, prio: MED

#91 Add YouTube Playlist input component to frontend
  ChordKTV/Controllers/SongController.cs
  frontend/lyric-sync-app/package-lock.json
  frontend/lyric-sync-app/package.json
  frontend/lyric-sync-app/src/api/.openapi-generator/FILES
  frontend/lyric-sync-app/src/api/apis/SongApi.ts
  frontend/lyric-sync-app/src/api/models/FullSongRequestDto.ts
  frontend/lyric-sync-app/src/api/models/PlaylistDetailsDto.ts
  frontend/lyric-sync-app/src/api/models/VideoInfo.ts
  frontend/lyric-sync-app/src/api/models/index.ts
  frontend/lyric-sync-app/src/components/YouTubePlaylistViewer.tsx
  frontend/lyric-sync-app/src/pages/HomePage.tsx
  frontend/lyric-sync-app/swagger.json
Labels: enhancement, prio: HIGH

#94 Frontend scrollable lyrics
  frontend/lyric-sync-app/package-lock.json
  frontend/lyric-sync-app/package.json
  frontend/lyric-sync-app/src/components/LyricDisplay/LyricDisplay.scss
  frontend/lyric-sync-app/src/components/LyricDisplay/LyricDisplay.tsx
  frontend/lyric-sync-app/src/pages/SongPlayerPage/SongPlayerPage.scss
  frontend/lyric-sync-app/src/pages/SongPlayerPage/SongPlayerPage.tsx
Labels: enhancement, prio: MED
