Repository darint916/Chord-KTV, pull requests merged in 2025-03, with the labels that each got.

#82 Parallel calls for yt playlists
  ChordKTV/Services/Service/YouTubeClientService.cs
Labels: enhancement, prio:LOW

#105 backend logic fix and simplificiation for gpt transl + rom
  ChordKTV/Services/Api/IGeniusService.cs
  ChordKTV/Services/Service/FullSongService.cs
  ChordKTV/Services/Service/GeniusService.cs
Labels: bug, prio: MED

#106 Backend duration adding
  ChordKTV/Dtos/FullSong/FullSongResponseDto.cs
  ChordKTV/Services/Service/FullSongService.cs
Labels: refactor, prio:LOW

#110 Backend gpt remedial query extraction
  ChordKTV/Dtos/OpenAI/CandidateSongInfo.cs
  ChordKTV/Dtos/OpenAI/CandidateSongInfoListResponse.cs
  ChordKTV/Dtos/SongDto.cs
  ChordKTV/README.md
  ChordKTV/Services/Api/IChatGptService.cs
  ChordKTV/Services/Service/ChatGptService.cs
  ChordKTV/Services/Service/FullSongService.cs
  ChordKTV/Utils/TextUtils.cs
  README.md
Labels: enhancement, prio: HIGH

#118 Replace youtube url with youtube id for API req
  frontend/lyric-sync-app/src/components/YouTubePlaylistViewer/YouTubePlaylistViewer.tsx
Labels: bug, enhancement, prio: HIGH

#119 Add extra boxes for lyrics, yt url
  frontend/lyric-sync-app/src/pages/HomePage/HomePage.tsx
Labels: enhancement, prio: HIGH

#128 import cleanup + spacing
  ChordKTV/Controllers/HandwritingController.cs
  ChordKTV/Controllers/UserController.cs
  ChordKTV/Data/Api/SongData/ISongRepo.cs
  ChordKTV/Data/AppDbContext.cs
  ChordKTV/Data/Repo/QuizData/QuizRepo.cs
  ChordKTV/Data/Repo/SongData/AlbumRepo.cs
  ChordKTV/Data/Repo/SongData/SongRepo.cs
  ChordKTV/Dtos/HandwritingCanvas/HandwritingCanvasRequestDto.cs
  ChordKTV/Dtos/HandwritingCanvas/HandwritingCanvasResponseDto.cs
  ChordKTV/Dtos/SongDto.cs
  ChordKTV/Dtos/VideoInfo.cs
  ChordKTV/Models/SongData/Album.cs
  ChordKTV/Models/SongData/GeniusMetaData.cs
  ChordKTV/Models/SongData/Song.cs
  ChordKTV/Models/UserData/User.cs
  ChordKTV/Profiles/QuizProfile.cs
  ChordKTV/Program.cs
  ChordKTV/Services/Api/IHandwritingService.cs
  ChordKTV/Services/Api/IQuizService.cs
  ChordKTV/Services/Service/ChatGptService.cs
  ChordKTV/Services/Service/HandwritingService.cs
  ChordKTV/Services/Service/QuizService.cs
  ChordKTV/Utils/CompareUtils.cs
  ChordKTV/Utils/KeywordExtractorUtils.cs
  ChordKTV/Utils/Shuffle.cs
Labels: refactor, prio:LOW

#137 Embedded player failing youtube bug fix
  ChordKTV/Services/Service/YouTubeClientService.cs
Labels: bug, prio: MED

#140 Backend gpt prompt revision fix
  ChordKTV/Dtos/OpenAI/TranslatedSongLyrics.cs
  ChordKTV/Services/Service/ChatGptService.cs
  ChordKTV/Services/Service/FullSongService.cs
  ChordKTV/Services/Service/YouTubeClientService.cs
Labels: bug, prio: HIGH

#83 GeniusMetaData Repository Refactoring
  ChordKTV/Controllers/SongController.cs
  ChordKTV/Data/Api/SongData/IGeniusMetaDataRepo.cs
  ChordKTV/Data/Api/SongData/ISongRepo.cs
  ChordKTV/Data/Repo/SongData/GeniusMetaDataRepo.cs
  ChordKTV/Data/Repo/SongData/SongRepo.cs
  ChordKTV/Dtos/SongDto.cs
  ChordKTV/Program.cs
  ChordKTV/Services/Service/GeniusService.cs
Labels: refactor, prio:LOW
