Repository darint916/Chord-KTV, pull requests merged in 2025-04, with the labels that each got.

#147 Reapply "LRCSearch: Add Artist and Title Alternates to Return DTO"
  ChordKTV/Dtos/LrcLyricsDto.cs
  ChordKTV/Services/Service/FullSongService.cs
  ChordKTV/Services/Service/LrcService.cs
Labels: bug

#146 Song matching score output to frontend add
  ChordKTV/Controllers/SongController.cs
  ChordKTV/Dtos/FullSong/FullSongResponseDto.cs
  ChordKTV/Dtos/LrcLyricsDto.cs
  ChordKTV/Dtos/MatchingScores.cs
  ChordKTV/Profiles/FullSongProfile.cs
  ChordKTV/Services/Api/IFullSongService.cs
  ChordKTV/Services/Service/FullSongService.cs
  ChordKTV/Services/Service/LrcService.cs
Labels: enhancement, question, prio:LOW

#150 Frontend handwriting quiz
  frontend/lyric-sync-app/src/App.tsx
  frontend/lyric-sync-app/src/api/apiClient.ts
  frontend/lyric-sync-app/src/components/AppBarComponent/AppBarComponent.tsx
  frontend/lyric-sync-app/src/components/HandwritingCanvas/HandwritingCanvas.scss
  frontend/lyric-sync-app/src/components/HandwritingCanvas/HandwritingCanvas.tsx
  frontend/lyric-sync-app/src/components/QuizComponent/QuizComponent.tsx
  frontend/lyric-sync-app/src/pages/HandwritingPage/HandwritingPage.scss
  frontend/lyric-sync-app/src/pages/HandwritingPage/HandwritingPage.tsx
  frontend/lyric-sync-app/tsconfig.app.json
Labels: enhancement, prio: HIGH

#81 Incorporate auth fully into backend
  ChordKTV/Controllers/SongController.cs
  ChordKTV/Controllers/UserController.cs
  ChordKTV/Data/Api/UserData/IUserRepo.cs
  ChordKTV/Data/Repo/UserData/UserRepo.cs
  ChordKTV/Dtos/UserDto.cs
  ChordKTV/Program.cs
  ChordKTV/Services/Api/IUserService.cs
  ChordKTV/Services/Service/UserService.cs
  frontend/lyric-sync-app/src/App.tsx
  frontend/lyric-sync-app/src/api/.openapi-generator/VERSION
  frontend/lyric-sync-app/src/api/apis/AuthApi.ts
  frontend/lyric-sync-app/src/api/apis/UserApi.ts
  frontend/lyric-sync-app/src/api/apis/index.ts
  frontend/lyric-sync-app/src/components/AppBarComponent/AppBarComponent.tsx
  frontend/lyric-sync-app/src/components/GoogleAuth/GoogleAuth.tsx
  frontend/lyric-sync-app/src/config/GoogleAuth.tsx
  frontend/lyric-sync-app/src/contexts/AuthContext.tsx
  frontend/lyric-sync-app/src/contexts/AuthTypes.tsx
  frontend/lyric-sync-app/src/pages/HomePage/HomePage.tsx
  frontend/lyric-sync-app/swagger.json
Labels: enhancement, prio: HIGH

#159 Frontend user report open GitHub issue with template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/search-play-report.md
  frontend/lyric-sync-app/src/_variables.scss
  frontend/lyric-sync-app/src/components/AppBarComponent/AppBarComponent.scss
  frontend/lyric-sync-app/src/components/AppBarComponent/AppBarComponent.tsx
Labels: enhancement, prio:LOW

#164 Unescape Quotes checker
  .editorconfig
  ChordKTV/Services/Service/ChatGptService.cs
Labels: bug, prio: MED

#170 Backend genius db save remove, add ID db Query matching
  ChordKTV/Data/Api/SongData/ISongRepo.cs
  ChordKTV/Data/Repo/SongData/SongRepo.cs
  ChordKTV/Services/Service/FullSongService.cs
  ChordKTV/Services/Service/GeniusService.cs
Labels: bug, prio: MED

#172 Backend genius search refinement fixes
  ChordKTV/Services/Service/FullSongService.cs
  ChordKTV/Services/Service/GeniusService.cs
  ChordKTV/Services/Service/LrcService.cs
Labels: bug, prio: HIGH

#173 artist checking LRC in best results grabbing
  ChordKTV/Services/Service/ChatGptService.cs
  ChordKTV/Services/Service/FullSongService.cs
  ChordKTV/Services/Service/GeniusService.cs
  ChordKTV/Services/Service/LrcService.cs
  ChordKTV/Utils/CompareUtils.cs
Labels: bug, prio: MED

#177 framechecking and efficient rerendering for youtube player
  ChordKTV/Services/Service/ChatGptService.cs
  ChordKTV/Services/Service/FullSongService.cs
  ChordKTV/Services/Service/GeniusService.cs
  frontend/lyric-sync-app/src/components/YouTubePlayer/YouTubePlayer.tsx
  frontend/lyric-sync-app/src/pages/SongPlayerPage/SongPlayerPage.tsx
Labels: bug, prio: HIGH

#175 Implement song queue on frontend
  frontend/lyric-sync-app/package-lock.json
  frontend/lyric-sync-app/package.json
  frontend/lyric-sync-app/src/_variables.scss
  frontend/lyric-sync-app/src/api/.openapi-generator/FILES
  frontend/lyric-sync-app/src/api/.openapi-generator/VERSION
  frontend/lyric-sync-app/src/api/apis/SongApi.ts
  frontend/lyric-sync-app/src/api/apis/UserApi.ts
  frontend/lyric-sync-app/src/api/apis/index.ts
  frontend/lyric-sync-app/src/api/models/FullSongResponseDto.ts
  frontend/lyric-sync-app/src/api/models/MatchScores.ts
  frontend/lyric-sync-app/src/api/models/index.ts
  frontend/lyric-sync-app/src/components/DraggableQueueItem/DraggableQueueItem.scss
  frontend/lyric-sync-app/src/components/DraggableQueueItem/DraggableQueueItem.tsx
  frontend/lyric-sync-app/src/components/DraggableQueueItem/PlaceholderThumbnail.scss
  frontend/lyric-sync-app/src/components/DraggableQueueItem/PlaceholderThumbnail.tsx
  frontend/lyric-sync-app/src/components/LyricDisplay/LyricDisplay.scss
  frontend/lyric-sync-app/src/components/LyricDisplay/LyricDisplay.tsx
  frontend/lyric-sync-app/src/components/QueueComponent/QueueComponent.scss
  frontend/lyric-sync-app/src/components/QueueComponent/QueueComponent.tsx
  frontend/lyric-sync-app/src/components/YouTubePlayer/YouTubePlayer.scss
  frontend/lyric-sync-app/src/components/YouTubePlayer/YouTubePlayer.tsx
  frontend/lyric-sync-app/src/components/YouTubePlaylistViewer/YouTubePlaylistViewer.scss
  frontend/lyric-sync-app/src/components/YouTubePlaylistViewer/YouTubePlaylistViewer.tsx
  frontend/lyric-sync-app/src/contexts/QueueTypes.tsx
  frontend/lyric-sync-app/src/contexts/SongContext.ts
  frontend/lyric-sync-app/src/contexts/SongContextProvider.tsx
  frontend/lyric-sync-app/src/pages/HomePage/HomePage.scss
  frontend/lyric-sync-app/src/pages/HomePage/HomePage.tsx
  frontend/lyric-sync-app/src/pages/HomePage/HomePageHelpers.ts
  frontend/lyric-sync-app/src/pages/SongPlayerPage/SongPlayerPage.scss
  frontend/lyric-sync-app/src/pages/SongPlayerPage/SongPlayerPage.tsx
  frontend/lyric-sync-app/swagger.json
Labels: enhancement, refactor, prio: HIGH

#195 Backend db dupe, missing search and precising search bug fix and cleanup
  ChordKTV/Services/Service/FullSongService.cs
  ChordKTV/Services/Service/GeniusService.cs
  ChordKTV/Utils/CompareUtils.cs
  ChordKTV/Utils/KeywordExtractorUtils.cs
  frontend/lyric-sync-app/src/components/QueueComponent/QueueComponent.tsx
  frontend/lyric-sync-app/src/components/YouTubePlaylistViewer/YouTubePlaylistViewer.tsx
  frontend/lyric-sync-app/src/pages/HomePage/HomePage.tsx
  frontend/lyric-sync-app/src/pages/SongPlayerPage/SongPlayerPage.tsx
Labels: prio: HIGH

#201 Add offset slider on frontend
  frontend/lyric-sync-app/src/pages/SongPlayerPage/SongPlayerPage.scss
  frontend/lyric-sync-app/src/pages/SongPlayerPage/SongPlayerPage.tsx
Labels: enhancement, prio: HIGH

#196 genius + lrclib endpoint search query results
  ChordKTV/Controllers/SongController.cs
  ChordKTV/Dtos/FullSong/FullSongResponseDto.cs
  ChordKTV/Dtos/LrcLib/LrcLyricsDto.cs
  ChordKTV/Dtos/LrcLib/LrcMetaDataDto.cs
  ChordKTV/Dtos/LrcLib/MatchingScores.cs
  ChordKTV/Profiles/LrcMetaDataProfile.cs
  ChordKTV/README.md
  ChordKTV/Services/Api/IGeniusService.cs
  ChordKTV/Services/Api/ILrcService.cs
  ChordKTV/Services/Service/FullSongService.cs
  ChordKTV/Services/Service/GeniusService.cs
  ChordKTV/Services/Service/LrcService.cs
  frontend/lyric-sync-app/src/api/apis/SongApi.ts
  frontend/lyric-sync-app/src/api/apis/index.ts
  frontend/lyric-sync-app/src/components/GoogleAuth/GoogleAuth.tsx
  frontend/lyric-sync-app/src/components/QueueComponent/QueueComponent.tsx
  frontend/lyric-sync-app/src/pages/HomePage/HomePage.tsx
  frontend/lyric-sync-app/src/pages/SongPlayerPage/SongPlayerPage.tsx
  frontend/lyric-sync-app/swagger.json
Labels: enhancement, prio: HIGH

#203 Necessary Setup for Deployment
  ChordKTV/Controllers/UserController.cs
  ChordKTV/Program.cs
  ChordKTV/appsettings.json
  frontend/lyric-sync-app/.env.example
  frontend/lyric-sync-app/README.md
  frontend/lyric-sync-app/src/api/apiClient.ts
  frontend/lyric-sync-app/src/components/GoogleAuth/GoogleAuth.tsx
  frontend/lyric-sync-app/tsconfig.app.json
Labels: prio: HIGH

#212 Search Cards Home Page
  frontend/lyric-sync-app/src/api/.openapi-generator/FILES
  frontend/lyric-sync-app/src/api/apis/SongApi.ts
  frontend/lyric-sync-app/src/api/models/GeniusAlbumDto.ts
  frontend/lyric-sync-app/src/api/models/GeniusHitDto.ts
  frontend/lyric-sync-app/src/api/models/GeniusResultDto.ts
  frontend/lyric-sync-app/src/api/models/index.ts
  frontend/lyric-sync-app/src/components/UserStats/MediaCarousel.tsx
  frontend/lyric-sync-app/src/pages/HomePage/HomePage.tsx
  frontend/lyric-sync-app/swagger.json
Labels: enhancement, prio: HIGH

#214 youtube better vid
  ChordKTV/Services/Service/YouTubeClientService.cs
Labels: enhancement, prio: MED

#225 Backend user activity count tracking
  ChordKTV/Controllers/UserActivityController.cs
  ChordKTV/Data/Api/UserData/IUserActivityRepo.cs
  ChordKTV/Data/Repo/UserData/UserActivityRepo.cs
  ChordKTV/Dtos/UserActivity/UserPlaylistActivityFavoriteRequestDto.cs
  ChordKTV/Dtos/UserActivity/UserSongActivityFavoriteRequestDto.cs
  frontend/lyric-sync-app/src/api/.openapi-generator/VERSION
  frontend/lyric-sync-app/src/api/models/FullSongResponseDto.ts
  frontend/lyric-sync-app/src/api/models/LearnedWordDto.ts
  frontend/lyric-sync-app/src/api/models/Song.ts
  frontend/lyric-sync-app/src/api/models/SongDto.ts
  frontend/lyric-sync-app/src/api/models/UserHandwritingResultDto.ts
  frontend/lyric-sync-app/src/api/models/UserPlaylistActivity.ts
  frontend/lyric-sync-app/src/api/models/UserPlaylistActivityDto.ts
  frontend/lyric-sync-app/src/api/models/UserPlaylistActivityFavoriteRequestDto.ts
  frontend/lyric-sync-app/src/api/models/UserQuizResultDto.ts
  frontend/lyric-sync-app/src/api/models/UserSongActivity.ts
  frontend/lyric-sync-app/src/api/models/UserSongActivityDto.ts
  frontend/lyric-sync-app/src/api/models/UserSongActivityFavoriteRequestDto.ts
  frontend/lyric-sync-app/src/api/runtime.ts
  frontend/lyric-sync-app/swagger.json
Labels: enhancement, finish asap

#226 Frontend build fixes (fr this time) (not clickbait)
  .github/workflows/react-build-check.yml
  frontend/lyric-sync-app/src/components/GeniusHitsCarousel/GeniusHitsCarousel.tsx
  frontend/lyric-sync-app/src/components/QuizComponent/QuizComponent.tsx
  frontend/lyric-sync-app/src/components/UserStats/KPIStrip.tsx
  frontend/lyric-sync-app/src/components/UserStats/LearnedWords.tsx
  frontend/lyric-sync-app/src/components/UserStats/MediaCarousel.tsx
  frontend/lyric-sync-app/src/contexts/SongContext.ts
  frontend/lyric-sync-app/src/pages/HandwritingPage/HandwritingPage.tsx
  frontend/lyric-sync-app/src/pages/HomePage/HomePage.tsx
  frontend/lyric-sync-app/src/pages/SongPlayerPage/SongPlayerPage.tsx
  frontend/lyric-sync-app/src/pages/UserStatsPage/UserStatsPage.tsx
Labels: finish asap

#227 Hook up user activity controller endpoints to frontend and more
  ChordKTV/Controllers/UserActivityController.cs
  ChordKTV/Data/Repo/UserData/UserActivityRepo.cs
  ChordKTV/Migrations/20250427034211_audiofuckery1.Designer.cs
  ChordKTV/Migrations/20250427034211_audiofuckery1.cs
  ChordKTV/Migrations/20250428175540_PlaylistRename.Designer.cs
  ChordKTV/Migrations/20250428175540_PlaylistRename.cs
  ChordKTV/Migrations/20250428201233_PlaylistTitle.Designer.cs
  ChordKTV/Migrations/20250428201233_PlaylistTitle.cs
  ChordKTV/Migrations/20250429035305_LateNights.Designer.cs
  ChordKTV/Migrations/20250429035305_LateNights.cs
  frontend/lyric-sync-app/src/components/HandwritingCanvas/HandwritingCanvas.tsx
  frontend/lyric-sync-app/src/components/QuizComponent/QuizComponent.tsx
  frontend/lyric-sync-app/src/components/UserStats/LearnedWords.tsx
  frontend/lyric-sync-app/src/components/UserStats/QuizResultsSection.module.scss
  frontend/lyric-sync-app/src/components/UserStats/TopPlaylists.tsx
  frontend/lyric-sync-app/src/pages/HandwritingPage/HandwritingPage.tsx
  frontend/lyric-sync-app/src/pages/HomePage/HomePage.tsx
  frontend/lyric-sync-app/src/pages/SongPlayerPage/SongPlayerPage.tsx
  frontend/lyric-sync-app/src/pages/UserStatsPage/UserStatsPage.module.scss
  frontend/lyric-sync-app/src/pages/UserStatsPage/UserStatsPage.tsx
  frontend/lyric-sync-app/src/pages/UserStatsPage/statsHelpers.ts
Labels: prio: HIGH
